version: '3.1'
services:
  app:
    container_name: docker-springboot-postgresql
    image: docker-springboot-postgresql
    networks:
      - my_network
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
    links:
      - postgresqldb
  postgresqldb:
    networks:
      - my_network
    image: postgres
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=postgres
      - POSTGRES_DB=moneyTransfer
networks:
  my_network:
    driver: bridge